name = "albaciete-eye-clinic"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "f42fc208-855c-42c9-8528-0f29eea5c9a8"
